spring:
  application:
    name: banking-zuul-gateway

server:
  port: 9010
  context-path: /banking/ 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

zuul:
  routes:
    banking-customer-api:
      path: /customers-api/**
      url: http://localhost:9015

    banking-account-api:
      path: /accounts-api/**
      serviceId: banking-account-api